version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[.stbl](feat/meta/deps):"
    labels:
      - dependencies

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[.stbl](feat/meta/ci):"
    labels:
      - dependencies
